'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'moving down',
'moving down',
'moving down',
'moving up',
'moving up',
'moving up',
'moving down',
'moving down',
'moving up',
'moving down',
'moving up',
'moving down',
'moving up',
'moving down',
'moving up',
'moving up',
'moving up',
'moving up',
'moving down',
'moving up',
'moving up',
'moving down',
'unchanged',
'moving up',
'moving down',
'moving down',
'moving down',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'unchanged',
'unchanged',
'moving up',
'moving down',
'moving down',
'moving up',
'moving up',
'moving up',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'moving up',
'moving up',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'unchanged',
'moving up',
'moving up',
'unchanged',
'moving up',
'moving up',
'moving down',
'moving up',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving down',
'unchanged',
'moving down',
'unchanged',
'moving up',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'moving down',
'unchanged',
'moving down',
'moving down',
'unchanged',
'moving down',
'unchanged',
'moving up',
'moving down',
'moving up',
'moving down',
'moving down',
'unchanged',
'moving down',
'unchanged',
'moving down',
'moving up',
'moving down',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'unchanged',
'moving up',
'moving up',
'unchanged',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving up',
'moving up',
'moving down',
'moving up',
'moving down',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'moving up',
'moving down',
'moving up',
'unchanged',
'moving up',
'moving down',
'moving up',
'moving down',
'moving up',
'unchanged',
'unchanged',
'moving down',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving up',
'unchanged',
'unchanged',
'moving up',
'unchanged',
'moving up',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'unchanged',
'moving down',
'moving up',
'moving down',
'moving down',
'unchanged',
'moving up',
'moving down',
'moving up',
'moving down',
'moving down',
'moving up',
'moving up',
'moving up',
'moving up',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'unchanged',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'unchanged',
'moving down',
'moving down',
'unchanged',
'moving up',
'unchanged',
'unchanged',
'moving down',
'unchanged',
'moving up',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving down',
'unchanged',
'unchanged',
'moving down',
'unchanged',
'moving up',
'unchanged',
'moving down',
'unchanged',
'moving up',
'moving down',
'unchanged',
'moving down',
'moving up',
'moving up',
'moving up',
'moving up',
'moving up',
'moving down',
'moving up',
'moving down',
'unchanged',
'moving up',
'moving down',
'moving up',
'moving up',
'moving up',
'moving up',
'moving down',
'unchanged',
'moving up',
'moving down',
'moving down',
'unchanged',
'moving up',
'moving up',
'moving down',
'unchanged',
'moving up',
'moving up',
'moving down',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving up',
'unchanged',
'moving down',
'moving up',
'moving up',
'moving down',
'moving down',
'unchanged',
'moving up',
'unchanged',
'moving down',
'moving down',
'moving up',
'unchanged',
'unchanged',
'moving down',
'moving down',
'moving down',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving down',
'moving up',
'moving down',
'unchanged',
'moving down',
'unchanged',
'moving down',
'moving up',
'unchanged',
'moving down',
'moving down',
'moving up',
'moving down',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving up',
'moving down',
'moving down',
'moving down',
'moving down',
'moving down',
'unchanged',
'moving down',
'moving down',
'moving up',
'moving up',
'unchanged',
'unchanged',
'moving down',
'unchanged',
'unchanged',
'unchanged',
'moving up',
'moving down',
'moving down',
'moving up',
'moving up',
'moving down',
'moving up',
'unchanged',
'moving down',
'moving up',
'moving down',
'moving up',
'unchanged',
'moving down',
'moving up',
'moving up',
'unchanged',
'moving down',
'moving down',
'moving up',
'moving down',
'moving down',
'moving up',
'moving down',
'moving up',
'moving up',
'unchanged',
'moving down',
'moving down',
'moving up',
'moving down',
'moving up',
'moving down',
'moving down'